site_name: Documentation Guide
site_description: Hitchhiker's Guide to Documentation
theme: readthedocs
pages:
- [index.md, Home]
- [language.md, Language]
- [formatting.md, Formatting]
- [process.md, Process]
- [metrics.md, Measuring Documentation Quality]
- [rolemodels.md, Role Models]
- [culture.md, Culture]
- [community.md, Community]
- [templates.md, Templates]
- [technologies.md, Technologies]
- [doctypes.md, Documentation Types]
- [tutorials.md, Tutorials]
- [presentations.md, Presentations]
- [meetings.md, Meeting Notes]
- [unclassified.md, Unclassified]
- [notes.md, Notes]