site_name: Documentation Guide
site_description: Hitchhiker's Guide to Documentation
theme: readthedocs
extra_css:
- style.css

pages:

- [index.md, Home]

- [general.md, For Everyone, General Notes]
- [doctypes.md, For Everyone, Documentation Types]
- [process.md, For Everyone, Process]

- [platform.md, For Organizers, Platform & Tools]
- [templates.md, For Organizers, Templates]
- [structure.md, For Organizers, Documentation Structure]
- [culture.md, For Organizers, Culture]
- [community.md, For Organizers, Community]

- [managing.md, For Managers, Managing People]
- [meetings.md, For Managers, Meeting Notes]

- [understandreader.md, For Writers, Understand Reader]
- [writing.md, For Writers, Writing Documentation]
- [tutorials.md, For Writers, Tutorials]

- [style.md, For Editors, Style]

- [ui.md, For Designers, UI]

- [measuring.md, For Analytics, Measuring Documentation Quality]

- [presentations.md, For Presenters, Presentations]

- [notes.md, Miscellaneous, Notes]