site_name: Documentation Guide
site_description: Hitchhiker's Guide to Documentation
theme: readthedocs
extra_css:
- style.css

pages:

- [index.md, Home]

- [general.md, For Everyone, General Notes]
- [doctypes.md, For Everyone, Documentation Types]
- [process.md, For Everyone, Process]

- [platform.md, For Organizers, Platform & Tools]
- [templates.md, For Organizers, Templates]
- [structure.md, For Organizers, Documentation Structure]
- [managing.md, For Organizers, Managing People]
- [culture.md, For Organizers, Culture]
- [community.md, For Organizers, Community]

- [writingprocess.md, For Writers, Writing Process]
- [tutorials.md, For Writers, Tutorials]

- [language.md, For Editors, Language]

- [ui.md, For Designers, UI]

- [metrics.md, For Analytics, Measuring Documentation Quality]

- [meetings.md, For Managers, Meeting Notes]

- [presentations.md, For Presenters, Presentations]

- [unclassified.md, Miscellaneous, Unclassified]
- [notes.md, Miscellaneous, Notes]