site_name: Documentation Guide
site_description: Hitchhiker's Guide to Documentation
theme: readthedocs
pages:
- [index.md, Home]

- [general.md, For All, General Notes]
- [doctypes.md, For All, Documentation Types]

- [process.md, Process]
- [rolemodels.md, Role Models]
- [culture.md, Culture]
- [community.md, Community]
- [templates.md, Templates]
- [technologies.md, Technologies]
- [tutorials.md, Tutorials]

- [language.md, For Editors, Language]

- [ui.md, For Designers, UI]

- [metrics.md, For Analytics, Measuring Documentation Quality]

- [meetings.md, For Managers, Meeting Notes]

- [presentations.md, For Presenters, Presentations]

- [unclassified.md, Miscellaneous, Unclassified]
- [notes.md, Miscellaneous, Notes]